# /home/marko/.config/tmuxinator/rpi_led.yml

name: rpi_led
root: ~/

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: 0

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1su

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - RPi SSH:
      layout: tiled
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      synchronize: after
      panes:
        - rpi0:
            - ssh pi@rpi0.local
            - cd catkin_ws/src/simple_ros_consensus/launch
            - clear
            - waitForRos; bash starter.sh
        - rpi1:
            - ssh pi@rpi1.local
            - cd catkin_ws/src/simple_ros_consensus/launch
            - clear
            - waitForRos; bash starter.sh
        - rpi2:
            - ssh pi@rpi2.local
            - cd catkin_ws/src/simple_ros_consensus/launch
            - clear
            - waitForRos; bash starter.sh
        - rpi3:
            - ssh pi@rpi3.local
            - cd catkin_ws/src/simple_ros_consensus/launch
            - clear
            - waitForRos; bash starter.sh
  - Local:
      layout: tiled
      panes:
        - roslaunch rpi_led_consensus main.launch
        - 
